### ISSUE TITLE
MSVC invalid

### ISSUE THREAD

**Issue by CraftSpider** [CraftedCart/specformatter#2]
https://github.com/CraftedCart/specformatter/blob/9c603bc2427870a899dcdc717427fe84f72d999c/CMakeLists.txt#L11

This line errors when compiling using windows' MSVC compiler, as it doesn't define `Wextra` or `Wpedantic`. Can be fixed with
```cmake
add_definitions(-Wall)
if(NOT WIN32)
    add_definitions(-Wextra -pedantic)
endif()
```

**Comment by CraftedCart** [comment]
Fixed!

I used
```cmake
#Be really pedantic!
if(MSVC)
    add_definitions(/W4)
else()
    add_definitions(-Wall -Wextra -pedantic)
endif()
```
instead for no particular reason other than that's what I've used on other projects ;P
